### ISSUE TITLE
Submitting ban...      Please, be patient. Do not close or reload the page!

### ISSUE THREAD

**Issue by helldorado** [allenta/varnish-bans-manager#10]
I Have this message  "Submitting ban...  Please, be patient. Do not close or reload the page!" 

The installation appears to be good and I can make bans manually from a console. 

Do you have any idea?

**Comment by davidfb** [comment]
Sorry for the late reply. There is indeed a problem with the example init.d scripts. Hopefully you'll all have found a workaround for it. Anyway, all these issues have been addressed before launching a new version for Varnish Bans Manager (v0.6.1) which is already available on Pypi (https://pypi.python.org/pypi/varnish-bans-manager) and Github (https://github.com/allenta/varnish-bans-manager/tree/0.6.1/). Besides fixing those scripts, several dependencies have been updated to keep up to date with their new releases. In particular, Django's dependency has been updated to 1.7.
