### ISSUE TITLE
[Feature Request] Include support for PURGE

### ISSUE THREAD

**Issue by cdgraff** [allenta/varnish-bans-manager#7]
Hi, will be possible include support for PURGE not only BAN? your gui is really excelent, and include Purge support will be very usefull.

Thanks

**Comment by davidfb** [comment]
Sorry for the late reply. Varnish Bans Manager internally uses the Varnish CLI (https://www.varnish-cache.org/docs/trunk/reference/varnish-cli.html) to send BANs, and the CLI does not support PURGEs. Therefore, this has to be marked as "won't fix". Sorry.
